CommunityPro/portfolio-html

README.md

Write a more descriptive README
closes #3

Add more descriptive README

---

README.md

Linked Enhancement badge

---

README.md

Externally linked the Contributing guidelines to the README

---

dist/css/style.css
dist/index.html
dist/js/script.js

Add code to check project structure

Add dummy code

---

.github/ISSUE_TEMPLATE/bug.md

Remove the auto-assignment on Eke

Remove issue assignment

---

README.md

Link badges in README to their respective labels

Linked bug badge

---

README.md

<!--Linked the good first issue batch>

Linked good first issue batch

---

README.md

Update the help wanted badge again.

updated help wanted badge.

---

template/css/custom.css
template/css/style.css

Add code requirement in comments

---

README.md

Add the link to raise an issue

Add link to raise issue

---

README.md

link open issues tab 

---

README.md

add sponsor/support button

---

template/css/utilities.css

add hover on button

---

README.md

add netlify deploy badge

---

README.md

- a new folder (favicon) was added in /portfolio-html/template/assets/
- requirements.md file was added

update project tree

---

README.md

Add a simple tutorial to explain how to customize this template. 
Closes #13

Add Template Steps

---

README.md

fix requirements link in readme

---

template/css/style.css
template/js/script.js

Make navigation responsive

---

template/css/style.css
template/css/utilities.css
template/index.html

- Add the about section
- Fix navigation issues
closes #57

Add about section

---

template/css/style.css

This pull request fixes the transparent navigation menu issue on mobile view. To do this I added a background to the navigation menu. In `style.css`:
```
.navbar .nav-menu {
background: var(--bg-primary);
}
```
https://github.com/CommunityPro/portfolio-html/issues/59
After fix:
Before:

Fix navigation

---

template/css/utilities.css

add background color  and top/bottom margin on 'connect with me' button.

add background on button

---

README.md

Add support and sponsor links to the README

Add support & sponsor link

---

README.md
template/index.html

Updates generated meta tags
[Issue Link](https://github.com/CommunityPro/portfolio-html/issues/65)

Generate Meta Tags

---

template/index.html

Add Fontawesome CDN link to head to allow font awesome icons to show.
[Issue Link](https://github.com/CommunityPro/portfolio-html/issues/68)

Add Font Awesome Link

---

template/css/style.css

It rotates and spaces the arrow icon attached to the resume button in the navbar.
[Issue link](https://github.com/CommunityPro/portfolio-html/issues/70)

Rotate Arrow Icon

---

template/index.html

changes 'visual design' to 'visual designer'

correct typo error

---

template/index.html

Change hero div to a semantic element

Change hero div to a semantic element

---

docs/css/utilities.css

Add transition to button
closes #63

Add transition to button

---

docs/index.html

Fixed Project navigation link not linked to the project section #91 by using the recommended fix 
[Project navigation link not linked to the project section #91](https://github.com/CommunityPro/portfolio-html/issues/91)

fixed: Project navigation link not linked to the project section #91

---

docs/css/utilities.css

add padding to the context-text

---

docs/index.html

Add Community Pro Watermark
This fixes issue No: #115

add footer attribution

---

src/css/style.css

add profile image animation

---

src/index.html
src/js/script.js

Updated files

---

src/index.html

Signed-off-by: Divine <deevynobeten@gmail.com>
It adds a target attribute to the links

Adding target attribute to links

---

README.md

Update README.md - Readme Typo fix 

---

src/index.html

Changed Works heading to Projects

Changed works to projects
